name = "stremio-addon-debrid-search"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[[env_vars]]
# Add your environment variables here
# Example:
# SWAGGER_USER = "your-username"
# SWAGGER_PASSWORD = "your-password"

[functions]
# Enable Node.js compatibility for Pages Functions
compatibility_flags = ["nodejs_compat"]
